---

Description: >-
  This template deploys a general purpose VPN to an existing VPC.

# Metadata:

Parameters:
  VpcShortName:
    Description: A short name that is prefixed to VPC resource names
    Type: String
  VpcStackName:
    Description: Name of an active CloudFormation stack that contains the VPC resources used in this stack
    Type: String

# Mappings:

# Conditions:

Resources:
  VpcVpnGateway:
    Type: AWS::EC2::VPNGateway
    Properties:
      Type: ipsec.1
      Tags:
        - Key: Name
          Value: !Sub "${VpcShortName}_VPC-VPG"
  VpcVpnGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Fn::ImportValue: !Sub "${VpcStackName}-VPCID"
      VpnGatewayId: !Ref VpcVpnGateway

# Outputs:
